#!/bin/bash

check=0

#Check if Axe.txt exists
if [ -e /cygdrive/c/Users/cmmann/Documents/unix_workshops/exercise4/World5/Level5-4/Another-Castle/Axe.txt ]; then
	#Check if Bridge.txt is gone
	if [ -e /cygdrive/c/Users/cmmann/Documents/unix_workshops/exercise4/World5/Level5-4/Another-Castle/Bridge.txt ]; then
		echo "The Bridge is still here!"
	else
		#Delete Bowser.txt only if Axe.txt exists AND Bridge.txt is gone
		rm Bowser.txt
		check=1
	fi
else
	echo "There is no Axe!"
fi

if [ $check == 1 ]; then
	echo "Mario used Axe."
	echo
	echo "It's super effective!"
	echo
	echo "Bowser fainted!"
	echo
	echo "
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZDMMMMDDDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNMMMMMMZ?INMMDDSSMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMM8DNNNMMD8OODNMN8=ZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNIOMMNDDDDDDDDD8I=ZMMMMDNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMN=~ZDD88888888ZI:=SMNONMOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMDMMMD+~~SOO8D88D8SS=:+78NMD77MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMOSDNMMO?~,~7ZO88D8OS77+?7S8DN8ZMMMMMNMMMMNMMMDDMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMZ?7ODDO?~,~ISOO888OOS7777SO88DDMMMMMDMNNDNMMMMDDMMMMMMMMMMMMMMMMMM
MMMMMMMMNNMMMMNOND88Z7?+ISZ8O8DOOOOSSSZOO8888NDD8ODMDSODNDM8DDMMMMMMMMMMMMMMMMMM
MMMMMMMMNM87I?78888OZZS7SZOOO8D8ZZOOOOOO88OOZ7===IDDMOSS8NNOZMDMMMMMMMMMMMMMMMMM
MMMMMMMMMND7~,,7ZO8OZZZZZOO8D8D888OZZOOOD88SS~,:?D8ODDOSS8NOS8NMMMMMMMMMMMMMMMMM
MMMMMMMMMMM8I==IZ8D8OOOOO88D8DD88D88O8888D8Z7+=?ZMZSZ8OSSZ8ZSZMDMMMMMMMMMMMMMMMM
MMMMMMMMMMDN8ISSO88888888D8O8D7Z8O88888OZO88SSSZDMOSSZZZSSZZSS8MMMMMMMMMMMMMMMMM
MMMMMMMMMMDNNOSO88OOOO88D8OZDS=?8OO88OZOZZO88OODDMNZSZZZZZSSSS8MMMMMMMMMMMMMMMMM
MMMMMMMMMDNND8888OOOZZO88OZ8D7:~Z8OO8ZOZSZZZSSDD8Z8MSZOOZOOZSSOMNMMMMMMMMMMMMMMM
MMMMMMMMNNOS8DD888OOOZO88ZODSI:,+OOO8ZZZS?~::=8D87OMSOOI~SOSSZDNNMNMMMMMMMMMMMMM
MMMMZMMMM87I87I77SZZOZO88ZZDS?:,=OZOOZOZ7~,:=7DD87SM8Z+,=O8ZZOMZO8NDMMMMMMMMMMMM
MZMI+MMMMOI7DI:::=SSZZZO8OZZSI:~IOZO8ZOS7?:~+8D887SM8?,,?8D888MOI78NDMMMMMMMMMMM
M?+,+MD?O87?OZ=,,:I7ZZZO8OOS77777SZO8ZOZ77IIZD8887SMO~,:I8DDD8ONOONMMMMMMMMMMMMM
MI+:I7,=D8?=ZN7~:+77ZZZO8OZOS777SZZO8OZZZ7SSZOO887SMS~,:?OO88OS8MNMMD~IMMMMMMMMM
MI?I+::7MO+:SD8ZIS7SZZZOD8OZZZZZZZO8D8OZZZZOOO8DO+SMS?=+IZOZZOZZMIMMMSZMMMMMMMMM
NO?+++=?ZN+.78ZSSSZOZZO88D8OOOOOOO8DDDD8OOOO88DO=?ONO7I7SZZ8OSZSNDMDNNMNNNMMMMMM
DN7+++?+?NS,:S88OZZZZO88O88D8888DDSI?III78D8DDZ~,?MDDS7ISOZZDDZS8MZ??I77ODDMNMMM
MMZI++++?OD+,:?S88OOO88OOOO88DDZI?:.    ,+I7S7~.,IM8S?~:~?SZDMOSD8OOI????IZ8DDMM
MDNSI+++?SMS,,.,++7ZDDDDDDDDS?=, .......  ..,...=D8+~:,,,,+ZODNOMMNNM87II???ZNDN
MNDNSI??7SONI:.. ..,:::::::~,........,,...... .,7MI:,,,,,,~+S8MDOS??SDDZSI???ONM
MMNDNO7ISZSONI:,................ .:+I7I7?~,..,:INO=,,,,,,,::=ZDZ+~~7??DNZ77IIZMM
MMMNDMNOOZZO8MOI~:,............,=?ZMMMMMM8I???SN8?=,,,,,,~~,,==:,:=I+:ZMDDDS?SMM
MMMMMDDNNN8DDZ8NO7~~:::::::~~+IZMMMNNNNNMMMMMMM8N?=:,,::=7+:,,,,,::~~~SMDND+,7NM
MMMMDD87IOND7~+8MM88ZZZZZZZO8MMMDDZZ77Z8NMNONDMMDI+=::~?8S+~:,,,,,,,:IDNDND?IDDN
MMMDNO7???Z8NODD8Z88DDDDDDDDD88Z7777SOMMMMNZNMMMNO7?+?Z8ZI7S~,,,,,,,~OMONMMDDDMM
MMMN8I?????78DO7IIIII7SSS77777777777ZNSOMN88DDDNMMNN88NDOODN?,,,,,,~7NOS8MMMNMMM
MMMMS???++?7Z7I7777777ZZS7ZS7777777?SMZDOZZSSII77SZZND==DMMMNDZ~,~?SDMZZDNMMMMMM
MMDN7??+++?I7777777777SZI+SZSSZZ7I??7MNOSSI?+++++++7MMNNZ??IISNDIZNMMMMDDMMMMMMM
MM8NI??+++??I777777777SZI==7?=?SZSSSOMOI7?++++++++7MMMMZ?+++++?ZNM8MMMMMMMMMMMMM
MMM?.,++++??I7??????777OO7?I?+==SI=~IMZ7?+++++++++S8NMO+++++++??INMMMMMMMMMMMMMM
MMN:.~?++???I????+++?77ODDOZI?++7?+=7MZI+++++++++IO,7NI++++++?I7ISMMMMMMMMMMMMMM
MMN7ISI++??????+++++?77ZNMNN8777Z777ZMO?+++++++++SMZ8Z+++++++++SZ8MMMMMMMMMMMMMM
MMMM7+?++II???+++++++ISONNMMNDDNNNNNDD8?++++++++?NMMNI+++++++++?88MMMMMMMMMMMMMM
MMMN,~I??77???+++++++I8MMMMMNMMMMMMMMNNI++++++++?MMMN?+++++??+++ONDMMMMMMMMMMMMM
MMMM87?I7D87I?++++++I8NDMMMMMMMMMMMMMMNZII++++++?MMMD?++++++?S7?7MMMMMMMMMMMMMMM
MMMMN+=8MDN8S7?+++?IONDMMMMMMMMMMMMMMNDDS777I???7M+=D++++++++IS7SMMMMMMMMMMMMMMM
MMMMNIONDMDNMDZSZZ8NNDMMMMMMMMMMMMMMMMNDN8S77777ZN77N?++++++++IODMMMMMMMMMMMMMMM
MMMMMMNDMMMMDMMMMMMDMMMMMMMMMMMMMMMMMMMNNMND8OOODDMMN7I??+++++?8NDMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMNMMM8ZSZSI???IMDMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDMMDNNNNDOZ7I78MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMNNZIS7ZDNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDNNNMDNMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMM"
fi
